### ISSUE TITLE
Inputs have different heights when using different label texts

### ISSUE THREAD

**Issue by randomBrainstormer** [yuritoledo/react-native-credit-card-input#32]
The label's width doesn't seem to adapt to the word length, causing different heights between the inputs. Example:  
![Schermata 2019-11-08 alle 15 58 04](https://user-images.githubusercontent.com/4858703/68486016-92116f00-0240-11ea-9b25-9658c3435d33.png)

**Comment by yuritoledo** [comment]
Hello @randomBrainstormer 

Do you mean, the "Expires In" field?

**Comment by yuritoledo** [comment]
Can you update version and check it again?

**Comment by randomBrainstormer** [comment]
Hi @yuritoledo! please allow me to explain myself better. I didn't mean just the wording, I intended the case when using a longer word in the label, such as using the word "Expires in" instead of just "Expiry" the input becomes "taller" because the word is longer and tries to fit it in the view and therefore breaks the alignment between the inputs. I was expecting all the inputs to remain the same height regardless of the label's word length. For now I have tried to abbreviate the words I'm using (because I'm translating the text to other languages) and this has solved my issue 😄

**Comment by yuritoledo** [comment]
![image](https://user-images.githubusercontent.com/18474538/69588321-fc5b3b00-0fc6-11ea-8d5b-14c403c353ea.png)

Fixed!
