### ISSUE TITLE
Image is cut off

### ISSUE THREAD

**Issue by nlshuynguyen** [yuritoledo/react-native-credit-card-input#36]
Should apply `resizeMode: "contain"`
![image](https://user-images.githubusercontent.com/53550422/68824283-eac18b80-06c8-11ea-89b1-3a1d7c989481.png)

**Comment by yuritoledo** [comment]
Hello,

It broken on android too?

**Comment by jsanchez-softdepot** [comment]
Hello, I can confirm that this issue is happening on Android too. I don't know if is there any fix for this already.

Thanks in advance.

**Comment by yuritoledo** [comment]
Fixes #36

**Comment by yuritoledo** [comment]
Width increased.
