### ISSUE TITLE
Dmiss Keyboard on complete all fields

### ISSUE THREAD

**Issue by zapcriativo** [yuritoledo/react-native-credit-card-input#37]
Hi, 

How to disable keyboard when fill all fields with valid value?

I did a function, but when CVV finishes it retraces to focus name again

`    const onChange = formData => {
      console.log(formData)
      state= {
        cartãoValido: false
      }

      // Check if card items is valid
      var name = formData.status.name;
      var number = formData.status.number;
      var expiry = formData.status.expiry;
      var cvc = formData.status.cvc;

      // Enable save button and dmiss keyboard
      if (name && number && expiry && cvc == 'valid') {
        Keyboard.dismiss()
        this.setState({cartãoValido: true})
      }

    }`

**Comment by yuritoledo** [comment]
Hello,

This is a default behavior. I don't agree with it.

I'll work on it in couple of days. If you want, feel free to open a PR.
