### ISSUE TITLE
Incomplete status on input fields- no indication to the user to correct 

### ISSUE THREAD

**Issue by vkkan** [yuritoledo/react-native-credit-card-input#44]
When user entered wrong input values i.e. incomplete data there was no visual indication to the user to complete the data entry for example
Entering card no : 4245784754857878 user wont taken to next input box nor red color , user will be in confusion state.

Please help me how to solve this

**Comment by yuritoledo** [comment]
Hello,

Is this cad number, a valid one?

**Comment by wagnerdelima** [comment]
@vkkan you can generate fake credit card numbers from here: https://www.getcreditcardinfo.com/generatevisacreditcard.php

**Comment by vkkan** [comment]
I have got those numbers from my testing team who was doing testing for the feature , I am not sure whether the card is valid or not but , even if the card was not valid then validator should show that input element as error but for now if we enter the sample card info which I have provided status was incomplete but for incomplete status there was no color indicator thats why user doesnt know what to do next

**Comment by vkkan** [comment]
> @vkkan you can generate fake credit card numbers from here: https://www.getcreditcardinfo.com/generatevisacreditcard.php

Yes, I can generate and use those numbers which was working fine but when validator fails to understand the card numbers we have entered the status of the card number field become incomplete state but for the user there was no visualisation what went wrong

**Comment by yuritoledo** [comment]
@vkkan Can you create a codesandbox to simulate the issue, please?
