### ISSUE TITLE
Form Vertifical

### ISSUE THREAD

**Issue by zapcriativo** [yuritoledo/react-native-credit-card-input#51]
Olá Yuri, 

Tudo bem?

Vi que comitou algo relacionado a ter o form na Vertical, essa feature já está funcionando? 

Se sim, como implementar?

**Comment by yuritoledo** [comment]
Olá, desculpe a demora.

Tente assim:
```
<CreditCardInput
        horizontal={false}
/>
```

Por favor, verifique o exemplo: `exampleVertical` para mais detalhes

**Comment by zapcriativo** [comment]
Olá, Yuri

Obrigado pelo retorno.

Tente, porém não deu certo :(

![image](https://user-images.githubusercontent.com/7153803/72684211-67a02580-3abd-11ea-975d-68982840a533.png)

![image](https://user-images.githubusercontent.com/7153803/72684219-7be42280-3abd-11ea-9464-499116c1bf06.png)

**Comment by yuritoledo** [comment]
Qual a versão que está usando, da lib?

**Comment by zapcriativo** [comment]
Instalei ele pelo Yarn, 

Tentei executar um yarn upgrade react-native-input-credit-card mas não mudou :(

Estranho que não retornou a versão no package.json 

![image](https://user-images.githubusercontent.com/7153803/72754615-13717000-3ba7-11ea-9cd4-cc403569fae3.png)

**Comment by yuritoledo** [comment]
Estranho mesmo :/

Tenta instalar via `yarn add` ou `npm install` mesmo, pois a versão que está no NPM está funcionando certinho

**Comment by zapcriativo** [comment]
Pois é, apaguei a versão a instalei novamente..

veio a 0.50 

    "react-native-input-credit-card": "^0.5.0",

Porém o horizontal false não funciona ainda
