### ISSUE TITLE
Request: fallback to default for `labels` and `placeholders` for `CreditCardInput`

### ISSUE THREAD

**Issue by murrple-1** [yuritoledo/react-native-credit-card-input#53]
Currently, if you use code like this
```js
return (<CreditCardInput
    labels={{
        number: "Numéro de Carte de Crédit"
    }} />
);
```
the other labels (for `cvc`, `expiry`, etc) will be blank/missing instead of filled in with their default values. It might be nice to fallback to their defaults.

Alternatively, if you'd prefer for some sort of form like this
```js
return (<CreditCardInput
    labels={{
        number: "Numéro de Carte de Crédit",
        cvc: CreditCardInput.defaultValues.labels.cvc,
        expiry: CreditCardInput.defaultValues.labels.expiry,
        ...
    }} />
);
```
then it would be appreciated if the `defaultValues` object was exposed via the `index.d.ts` for Typescript users as well.

**Comment by yuritoledo** [comment]
Hello,

Can you create a sandbox?

**Comment by murrple-1** [comment]
Please define "sandbox". I'm not familiar with it in this context.

**Comment by yuritoledo** [comment]
Sorry, my mistake.

This is a sandbox, here you can recreate your environment
https://codesandbox.io/

Then, share here the link to access it.
