### ISSUE TITLE
Deprecation Warning firing for `CreditCardInput` on `focus`

### ISSUE THREAD

**Issue by murrple-1** [yuritoledo/react-native-credit-card-input#54]
The `_focus()` method in the `CreditCardInput` is using the `NativeModules` FFI to call `UIManager.measureLayoutRelativeToParent()`, which is being deprecated in a future version of React-Native. A big warning is being displayed in the app in development mode.

See: https://github.com/facebook/react-native/commit/e42009b7849f1cfd6d6d34e28c564ec5e39680bb

**Comment by yuritoledo** [comment]
Great.

Can you create a PR?
